// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlkcdcgcenswqjbsxoii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsa2NkY2djZW5zd3FqYnN4b2lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NDAwMDksImV4cCI6MjA1NTQxNjAwOX0.W6c41ccHFNFlXtZD0MJUlgNex5qfkTXGIvcoCKA6Pi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);